### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/pathvisio4-ant#11]
The databases loaded for annotations are all currently in the BridgeDb datasources.tsv, this will not help people make the right decision: 
![image](https://user-images.githubusercontent.com/26277832/169979274-e0509494-a3e0-4ebe-a71d-aa979b48a04a.png)
 (e.g. for Geneproduct DataNodes, there's a selection of relevant databases,  which is also implemented for Metabolites).

**Comment by DeniseSl22** [comment]
Url link should be URL link (so with full caps).

**Comment by DeniseSl22** [comment]
What does the * mean? As in, value and Type are mandatory, and the rest is not?

**Comment by DeniseSl22** [comment]
For Type, I can select "Ontology", "Taxonomy", and "Undefined". I would call "undefined" "Other".

**Comment by DeniseSl22** [comment]
Apparently I can select a database called "original"? Not sure if that belongs here, or should be fixed in BridgeDB.... 
![image](https://user-images.githubusercontent.com/26277832/169980010-6fe1b560-0c72-4b0b-ab2a-e153b162cc7d.png)

**Comment by Finterly** [comment]
Commits 9931f5e  and  ffee76b resolves most of these issues.
