### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/pathvisio4-ant#12]
When I want to add a citation, and click the "search PubMed" button, I see a pop-up menu, which appears after some seconds, but I don't see if the search worked. Maybe displaying another pop-up menu stating: "citation found for (ID user added)", would help users to understand the search actually worked (you would normally see that when all field were filled in). Also, what happens if the search doesn't work? I tried to search for PubMed ID "1", the same thing as a above happened, only when I clicked "Ok", I got a warning message (meaning the search didn't retrieve any results I assume). I would think that a second pop-up, stating "your search with PMID (IS users added) did not retrieve any results" would again be very useful.

**Comment by DeniseSl22** [comment]
This error message is not what you want people to do, right (I searched for PMID 1, again)? As in, when I fill in an ID which doesn't retrieve results, I want people to actually fix the ID, not add a database and be able to add the citation anyway (see second printscreen) 
![image](https://user-images.githubusercontent.com/26277832/169981028-321e25b6-b4bd-443c-9803-410eef266f8c.png)
![image](https://user-images.githubusercontent.com/26277832/169981279-bb463189-c641-4a0f-b311-2817991320fd.png)

**Comment by DeniseSl22** [comment]
I can add DOIs as PubMed, and vice versa (I think checking for the content of the ID shouldn't be difficult right? a DOI always contains a / I believe, while a PMID has a specific length and should only be numeric); and also, we don't want people to put in PubMed central IDs iso PMID, right?
![image](https://user-images.githubusercontent.com/26277832/169981848-70a996f3-4b56-41a4-ac34-154f1df07b9f.png)

**Comment by DeniseSl22** [comment]
Why do we actually still have a "Query Pubmed" button? Is this there to check if the ID is valid? Since the additional info regarding the citation is not stored in GPML2021 anymore, right?

**Comment by egonw** [comment]
> Why do we actually still have a "Query Pubmed" button?

I looked into a "Query Crossref" (for DOIs) before and will not hard to add.

**Comment by mkutmon** [comment]
I agree about the "Query Pubmed" button. That can be removed. And some basic checking of the pattern is a good idea.

**Comment by egonw** [comment]
A counter argument that came up yesterday is that the button is a way for the user to check if the have the correct identifier. Better see that while the dialog is open, then after.

**Comment by DeniseSl22** [comment]
Yes, it's very relevant for users to check.... but, if there's a button that you click which doesn't show any output, it's a bit confusing. Having a pop-up that shows the "retrieved" data from pubmed/DOI, with a button in the pop-up saying "accept reference" or decline", that would be really useful for data curation.
