### ISSUE TITLE
Group types and styles

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/pathvisio4-ant#15]
Why can I select so many option, when I want to connect two proteins?
![image](https://user-images.githubusercontent.com/26277832/169985668-1831296a-2846-4a81-be42-6d1b1970fb21.png)

**Comment by DeniseSl22** [comment]
What does analog and paralog mean in this case?

**Comment by DeniseSl22** [comment]
What is a "transparent" group?

**Comment by DeniseSl22** [comment]
When I have created a group, I get the option to "add alias", which places an Alias concept next to the group. When I move the group to another location on the canvas, the alias doesn't move along (as in, it's not included in the group).

**Comment by DeniseSl22** [comment]
When I select an "Alias", I get the option in the Properties menu to select the DataNode type "complex", which is not therein the concepts/molecular Object menu? 
![image](https://user-images.githubusercontent.com/26277832/169986801-52045594-c977-48d1-809e-67dc86799ae5.png)

**Comment by Finterly** [comment]
It would be nice to add some information in the hover over rather than just "Group selected elements".

@AlexanderPico  Could you suggest a suitable description for Analog and Paralog? 

![image](https://user-images.githubusercontent.com/28988687/176374846-567323bc-22ea-43bd-a03d-ac50a45eaf19.png)

**Comment by Finterly** [comment]
Added hover information for groups commit e7e2008
