### ISSUE TITLE
labels of themes not fully readable

### ISSUE THREAD

**Issue by egonw** [PathVisio/pathvisio4-ant#19]
Linux/J11.

![image](https://user-images.githubusercontent.com/26721/171617609-ce4213f2-fb02-4b4d-8283-c897825fa4d6.png)

**Comment by egonw** [comment]
(and WikiPathways with a capital P)

**Comment by Finterly** [comment]
There are currently two themes. One is "WikiPathways" and the other is "WikiPathways minimal". @mkutmon, should I remove the second theme "WikiPathways minimal"? It is the same as WikiPathways, but it also make shapes gray/black.

**Comment by Finterly** [comment]
Removed "WikiPathways Minimal" theme as it is not needed as per commit 1af1001
