### ISSUE TITLE
Edit>Search Pathways doesn't work

### ISSUE THREAD

**Issue by khanspers** [PathVisio/pathvisio4-ant#42]
Selecting Edit>Search Pathways seems to do nothing? I was expecting a search field somewhere but nothing changes in the interface. Also no NPE or error message. 

(MacOS Catalina, 10.15.7)

**Comment by Finterly** [comment]
@mkutmon I believe we decided to remove the "Search Pathways" from PathVisio4. I forgot to remove the Edit>Search Pathways option, I will do so now.

**Comment by Finterly** [comment]
Removed Search Pathways as per commit 489cfd0
