### ISSUE TITLE
Suggestion: Change the Edit>Selection menu item 

### ISSUE THREAD

**Issue by khanspers** [PathVisio/pathvisio4-ant#43]
The menu option "Edit>Selection" contains the set of tools for manipulating a set of selected nodes in terms of layout, sizing and stacking. I find the menu item "Selection" kind of confusing and I'm not sure users would look under it for that kind of functionality. How about Layout Tools (like in Cytoscape) or similar?

**Comment by Finterly** [comment]
Thank you. I also think "Layout Tools" makes make sense. I have made the change as per commit 72c4d9d
