### ISSUE TITLE
Objects menu issues

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/pathvisio4-ant#9]
I believe the top layer in the Objects menu should be called "Molecular", not "molecules" (I think this is a bit confusing for people more into genetics).

**Comment by DeniseSl22** [comment]
I would call the interaction panel just "interactions" (because all of these are panels).

**Comment by DeniseSl22** [comment]
I would call "miscellaneous shapes" something else (because now it sounds like a negative thing), for example: "Cell elements". I would also suggest to have a look at the Reactome icon library, they use a classification style as well: 
![image](https://user-images.githubusercontent.com/26277832/169973450-5e969b84-5bfc-4b51-aedf-a68c25246a2c.png)

**Comment by DeniseSl22** [comment]
I like all the additional shapes (now under miscellaneous), expect for the circle with the diagonal line through it (what is that used for? I believe it's part if another drawing style, SBGN? but there the diagonal line is going from top left to bottom right)....) Also, this shape used to be part of the "graphical elements", why is it not there anymore?
![image](https://user-images.githubusercontent.com/26277832/169974453-47dbdb41-e0b6-4b1d-8ad0-c59930551b14.png)

**Comment by DeniseSl22** [comment]
The lipid bilayer is not rendered correctly, the bottom part is slightly cut off:
Top:
![image](https://user-images.githubusercontent.com/26277832/169974693-bb4d3f14-9e7d-485a-96c8-d7dc7393954f.png)

Bottom:
![image](https://user-images.githubusercontent.com/26277832/169974641-8d89a147-67b4-4ea0-b7fc-f33d4ef62b52.png)

**Comment by DeniseSl22** [comment]
The hover function to explain what the interactions mean does not seem to work now (which is really needed to understand the subtle differences between different arrowheads).

**Comment by DeniseSl22** [comment]
The interaction panel contains three arrowheads, which are visually not easy to differentiate from one another:
![image](https://user-images.githubusercontent.com/26277832/169975222-e56bef18-8738-43a8-a6d0-a495e5b56b26.png)

The first one is "directed", the second "conversion", the third "translocation". People will make mistakes, if there is no clear difference visually, as well as putting two similar looking arrows right next to each other in the panel.

**Comment by DeniseSl22** [comment]
Why do interactions start type are called "undirected"? I believe this used to be called " line"?
![image](https://user-images.githubusercontent.com/26277832/169975618-4535c41b-e794-44c6-bc0e-e26c03b4eead.png)

**Comment by AlexanderPico** [comment]
For me (on a mac), the panel starts just a bit too narrow, making everything look bad. If the default width at start could be a little wider, that would be better.

**Comment by mkutmon** [comment]
> For me (on a mac), the panel starts just a bit too narrow, making everything look bad. If the default width at start could be a little wider, that would be better.

doesn't that depend on the screen size as well? but I think it should be possible to fix a minimum width.

**Comment by mkutmon** [comment]
> I would call "miscellaneous shapes" something else (because now it sounds like a negative thing), for example: "Cell elements"

I don't think of something negative related to "miscellaneous" - it's a collection of "other" shapes or not?

**Comment by mkutmon** [comment]
> Why do interactions start type are called "undirected"? I believe this used to be called " line"? ![image](https://user-images.githubusercontent.com/26277832/169975618-4535c41b-e794-44c6-bc0e-e26c03b4eead.png)

decision in GPML2021 to remove Line and other "unsemantic" labels - not sure what we should replace it with besides "undirected"

**Comment by Finterly** [comment]
Renamed the layers/titles as per commit d817731
